name: Test with version

on:
  push:
    branches:    
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: Blaze2305/better-aws-iam-authenticator-action@master
      with:
        version: 0.5.2

    - name: Version 0.5.0 of AWS IAM Authenticator
      run: aws-iam-authenticator version